-- Add cumulative KPI support: relation table and calculation_type extension

-- Create table to store cumulative source relations (many-to-many)
CREATE TABLE IF NOT EXISTS public.kpi_cumulative_sources (
  kpi_id uuid NOT NULL REFERENCES public.kpis(id) ON DELETE CASCADE,
  source_kpi_id uuid NOT NULL REFERENCES public.kpis(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (kpi_id, source_kpi_id)
);

ALTER TABLE public.kpi_cumulative_sources ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_cumulative_sources' AND policyname = 'kpi_cumulative_sources_select'
  ) THEN
    CREATE POLICY kpi_cumulative_sources_select ON public.kpi_cumulative_sources
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_cumulative_sources' AND policyname = 'kpi_cumulative_sources_insert'
  ) THEN
    CREATE POLICY kpi_cumulative_sources_insert ON public.kpi_cumulative_sources
      FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_cumulative_sources' AND policyname = 'kpi_cumulative_sources_delete'
  ) THEN
    CREATE POLICY kpi_cumulative_sources_delete ON public.kpi_cumulative_sources
      FOR DELETE
      TO authenticated
      USING (true);
  END IF;
END $$;

-- Extend calculation_type to include 'cumulative'
DO $$
BEGIN
  -- Try to drop the existing autogenerated check constraint if present
  BEGIN
    ALTER TABLE public.kpis DROP CONSTRAINT IF EXISTS kpis_calculation_type_check;
  EXCEPTION WHEN undefined_object THEN
    -- ignore if constraint name differs
    NULL;
  END;

  ALTER TABLE public.kpis ADD CONSTRAINT kpis_calculation_type_check CHECK (
    calculation_type IN ('direct', 'percentage', 'cumulative', 'formula', 'target')
  );
END $$;

COMMENT ON COLUMN public.kpis.calculation_type IS 'Type of calculation: direct (manual), percentage (numerator/denominator), cumulative (sum of source KPIs)';