-- Add formula KPI support: expression table and calculation_type extension

-- Table to store formula expressions per KPI (referencing other KPIs via ID tokens)
CREATE TABLE IF NOT EXISTS public.kpi_formulas (
  kpi_id uuid NOT NULL REFERENCES public.kpis(id) ON DELETE CASCADE,
  expression text NOT NULL, -- normalized expression using KPI ID tokens, e.g., {{<uuid>}} + {{<uuid>}} - ...
  display_expression text,  -- optional human-readable expression with KPI names (for UI)
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (kpi_id)
);

ALTER TABLE public.kpi_formulas ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_formulas' AND policyname = 'kpi_formulas_select'
  ) THEN
    CREATE POLICY kpi_formulas_select ON public.kpi_formulas
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_formulas' AND policyname = 'kpi_formulas_insert'
  ) THEN
    CREATE POLICY kpi_formulas_insert ON public.kpi_formulas
      FOR INSERT
      TO authenticated
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'kpi_formulas' AND policyname = 'kpi_formulas_delete'
  ) THEN
    CREATE POLICY kpi_formulas_delete ON public.kpi_formulas
      FOR DELETE
      TO authenticated
      USING (true);
  END IF;
END $$;

-- Extend calculation_type to include 'formula'
DO $$
BEGIN
  -- Try to drop the existing autogenerated check constraint if present
  BEGIN
    ALTER TABLE public.kpis DROP CONSTRAINT IF EXISTS kpis_calculation_type_check;
  EXCEPTION WHEN undefined_object THEN
    -- ignore if constraint name differs
    NULL;
  END;

  ALTER TABLE public.kpis ADD CONSTRAINT kpis_calculation_type_check CHECK (
    calculation_type IN ('direct', 'percentage', 'cumulative', 'formula', 'target')
  );
END $$;

COMMENT ON COLUMN public.kpis.calculation_type IS 'Type of calculation: direct (manual), percentage (numerator/denominator), cumulative (sum), formula (expression of other KPIs)';